# Generated by Django 5.2.3 on 2025-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_amount_alter_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('requires_payment_method', 'Méthode de paiement requise'), ('requires_confirmation', 'Confirmation requise'), ('requires_action', 'Action requise'), ('processing', 'En traitement'), ('canceled', 'Annulé')], default='pending', max_length=25),
        ),
    ]
