# Generated by Django 5.2.3 on 2025-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('requires_payment_method', 'Méthode de paiement requise'), ('requires_confirmation', 'Confirmation requise'), ('requires_action', 'Action requise'), ('processing', 'En traitement'), ('canceled', 'Annulé')], default='requires_payment_method', max_length=25),
        ),
    ]
