# Generated by Django 5.2.3 on 2025-10-16 16:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_quantity_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('requires_payment_method', 'Méthode de paiement requise'), ('requires_confirmation', 'Confirmation requise'), ('requires_action', 'Action requise'), ('processing', 'En traitement'), ('canceled', 'Annulé'), ('transferred', 'Transféré au vendeur')], default='requires_payment_method', max_length=25),
        ),
    ]
