# Generated by Django 5.2.3 on 2025-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('requires_payment_method', 'Méthode de paiement requise'), ('requires_confirmation', 'Confirmation requise'), ('requires_action', 'Action requise'), ('processing', 'En traitement'), ('canceled', 'Annulé'), ('transferred', 'Transféré au vendeur')], default='pending', max_length=25),
        ),
    ]
