# Generated by Django 5.2.3 on 2026-02-28 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_remove_order_buyer_alter_order_status_and_more'),
        ('listings', '0010_alter_listingview_session_key'),
        ('payments', '0009_transaction_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('held', 'En escrow'), ('refunded', 'Remboursé'), ('released', 'Released to seller'), ('requires_payment_method', 'Méthode de paiement requise'), ('requires_confirmation', 'Confirmation requise'), ('requires_action', 'Action requise'), ('processing', 'En traitement'), ('canceled', 'Annulé'), ('transferred', 'Transféré au vendeur')], default='pending', max_length=25),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'status'], name='payments_tr_order_i_028313_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_tr_stripe__2131ca_idx'),
        ),
    ]
