# Generated by Django 5.2.3 on 2026-02-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='user',
        ),
    ]
