# Generated by Django 5.2.3 on 2025-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('failed', 'Échouée')], default='pending', max_length=20),
        ),
    ]
