# Generated by Django 5.2.3 on 2025-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('ready_to_ship', 'Prêt à expédier'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('failed', 'Échouée'), ('returned', 'Retourné')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
