# Generated by Django 5.2.3 on 2026-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('ready_to_ship', 'Prêt à expédier'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('returned', 'Retourné')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
