# Generated by Django 5.2.3 on 2026-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_delivery_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel auto envoyé'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation réception'),
        ),
        migrations.AddField(
            model_name='order',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mis en attente'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_escrow',
            field=models.BooleanField(default=True, verbose_name='En escrow'),
        ),
        migrations.AddField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Libéré'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition"),
        ),
    ]
