# Generated by Django 5.2.3 on 2026-02-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_remove_order_buyer_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='listing',
        ),
    ]
