# Generated by Django 5.2.3 on 2025-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin_user_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur'), ('admin', 'Administrateur')], default='buyer', max_length=10),
        ),
    ]
