# Generated by Django 5.2.3 on 2025-06-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_admin_remove_user_is_seller_user_role'),
    ]

    operations = [
    ]
