# Generated by Django 5.2.3 on 2025-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250630_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+213', 'Algérie (+213)'), ('+229', 'Bénin (+229)'), ('+226', 'Burkina Faso (+226)'), ('+237', 'Cameroun (+237)'), ('+238', 'Cap-Vert (+238)'), ('+236', 'Centrafrique (+236)'), ('+235', 'Tchad (+235)'), ('+269', 'Comores (+269)'), ('+242', 'Congo-Brazzaville (+242)'), ('+243', 'RD Congo (+243)'), ('+225', 'Côte d’Ivoire (+225)'), ('+240', 'Guinée équatoriale (+240)'), ('+241', 'Gabon (+241)'), ('+220', 'Gambie (+220)'), ('+233', 'Ghana (+233)'), ('+224', 'Guinée (+224)'), ('+245', 'Guinée-Bissau (+245)'), ('+254', 'Kenya (+254)'), ('+266', 'Lesotho (+266)'), ('+231', 'Libéria (+231)'), ('+218', 'Libye (+218)'), ('+261', 'Madagascar (+261)'), ('+265', 'Malawi (+265)'), ('+223', 'Mali (+223)'), ('+222', 'Mauritanie (+222)'), ('+230', 'Maurice (+230)'), ('+262', 'Mayotte (+262)'), ('+212', 'Maroc (+212)'), ('+258', 'Mozambique (+258)'), ('+264', 'Namibie (+264)'), ('+227', 'Niger (+227)'), ('+234', 'Nigéria (+234)'), ('+250', 'Rwanda (+250)'), ('+239', 'Sao Tomé-et-Principe (+239)'), ('+221', 'Sénégal (+221)'), ('+248', 'Seychelles (+248)'), ('+232', 'Sierra Leone (+232)'), ('+252', 'Somalie (+252)'), ('+27', 'Afrique du Sud (+27)'), ('+211', 'Soudan du Sud (+211)'), ('+249', 'Soudan (+249)'), ('+255', 'Tanzanie (+255)'), ('+228', 'Togo (+228)'), ('+216', 'Tunisie (+216)'), ('+256', 'Ouganda (+256)'), ('+260', 'Zambie (+260)'), ('+263', 'Zimbabwe (+263)'), ('+43', 'Autriche (+43)'), ('+32', 'Belgique (+32)'), ('+359', 'Bulgarie (+359)'), ('+385', 'Croatie (+385)'), ('+357', 'Chypre (+357)'), ('+420', 'République Tchèque (+420)'), ('+45', 'Danemark (+45)'), ('+372', 'Estonie (+372)'), ('+358', 'Finlande (+358)'), ('+33', 'France (+33)'), ('+49', 'Allemagne (+49)'), ('+30', 'Grèce (+30)'), ('+36', 'Hongrie (+36)'), ('+353', 'Irlande (+353)'), ('+39', 'Italie (+39)'), ('+371', 'Lettonie (+371)'), ('+370', 'Lituanie (+370)'), ('+352', 'Luxembourg (+352)'), ('+31', 'Pays-Bas (+31)'), ('+48', 'Pologne (+48)'), ('+351', 'Portugal (+351)'), ('+40', 'Roumanie (+40)'), ('+421', 'Slovaquie (+421)'), ('+386', 'Slovénie (+386)'), ('+34', 'Espagne (+34)'), ('+46', 'Suède (+46)'), ('+41', 'Suisse (+41)'), ('+44', 'Royaume-Uni (+44)'), ('+93', 'Afghanistan (+93)'), ('+880', 'Bangladesh (+880)'), ('+86', 'Chine (+86)'), ('+91', 'Inde (+91)'), ('+62', 'Indonésie (+62)'), ('+81', 'Japon (+81)'), ('+82', 'Corée du Sud (+82)'), ('+60', 'Malaisie (+60)'), ('+95', 'Myanmar (+95)'), ('+92', 'Pakistan (+92)'), ('+63', 'Philippines (+63)'), ('+65', 'Singapour (+65)'), ('+66', 'Thaïlande (+66)'), ('+84', 'Vietnam (+84)'), ('+54', 'Argentine (+54)'), ('+55', 'Brésil (+55)'), ('+56', 'Chili (+56)'), ('+57', 'Colombie (+57)'), ('+53', 'Cuba (+53)'), ('+593', 'Équateur (+593)'), ('+502', 'Guatemala (+502)'), ('+504', 'Honduras (+504)'), ('+52', 'Mexique (+52)'), ('+1', 'États-Unis (+1)'), ('+598', 'Uruguay (+598)'), ('+58', 'Venezuela (+58)'), ('+61', 'Australie (+61)'), ('+64', 'Nouvelle-Zélande (+64)'), ('+675', 'Papouasie-Nouvelle-Guinée (+675)')], default='+225', max_length=4, verbose_name='Indicatif pays'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
    ]
