# Generated by Django 5.2.3 on 2025-10-08 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_service_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_service_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('individual', 'Individuel'), ('company', 'Entreprise')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('carte-identite', "Carte d'identité"), ('passeport', 'Passeport'), ('permis-conduire', 'Permis de conduire')], max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_address', models.TextField(blank=True, null=True)),
                ('shipping_zone', models.CharField(choices=[('Bamako', 'Bamako'), ('Ségou', 'Ségou'), ('Koulikoro', 'Koulikoro')], default='Bamako', max_length=50)),
                ('use_business_address', models.BooleanField(default=False)),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('return_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('return_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('return_city', models.CharField(blank=True, max_length=100, null=True)),
                ('return_state', models.CharField(blank=True, max_length=100, null=True)),
                ('return_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('has_existing_shop', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=3, null=True)),
                ('vendor_type', models.CharField(blank=True, choices=[('retailer', 'Détaillant'), ('wholesaler', 'Grossiste'), ('manufacturer', 'Fabricant'), ('distributor', 'Distributeur'), ('individual', 'Particulier')], max_length=20, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Vendeur',
                'verbose_name_plural': 'Profils Vendeurs',
            },
        ),
    ]
