# Generated by Django 5.2.3 on 2025-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('Bamako', 'Bamako'), ('Kayes', 'Kayes'), ('Koulikoro', 'Koulikoro'), ('Sikasso', 'Sikasso'), ('Ségou', 'Ségou'), ('Mopti', 'Mopti'), ('Tombouctou', 'Tombouctou'), ('Gao', 'Gao'), ('Kidal', 'Kidal')], max_length=100, null=True, verbose_name='Région'),
        ),
    ]
