# Generated by Django 5.2.3 on 2025-10-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('active_products', models.IntegerField(default=0)),
                ('out_of_stock_products', models.IntegerField(default=0)),
                ('draft_products', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_shipping_time', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques Vendeur',
                'verbose_name_plural': 'Statistiques Vendeurs',
            },
        ),
        migrations.CreateModel(
            name='VendorDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders_count', models.IntegerField(default=0)),
                ('products_sold', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique Quotidienne',
                'verbose_name_plural': 'Statistiques Quotidiennes',
                'ordering': ['-date'],
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
