# Generated by Django 5.2.3 on 2025-10-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_vendorstats_vendordailystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorstats',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='VendorDailyStats',
        ),
        migrations.DeleteModel(
            name='VendorStats',
        ),
    ]
