# Generated by Django 5.2.3 on 2025-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_vendorstats_vendor_delete_vendordailystats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
