# Generated by Django 5.2.3 on 2025-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_vendorprofile_business_license_vendorprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
