# Generated by Django 5.2.3 on 2026-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_vendorprofile_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_full',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
