# Generated by Django 5.2.3 on 2026-02-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_registration',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/business/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id_back/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id_front/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/address/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
