# Generated by Django 5.2.3 on 2026-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_vendorprofile_business_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
