# Generated by Django 5.2.3 on 2026-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_vendorprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfie/'),
        ),
    ]
