# Generated by Django 5.2.3 on 2026-02-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_vendorprofile_selfie_with_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorKYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front_image', models.ImageField(upload_to='kyc_records/id_front/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='kyc_records/id_back/')),
                ('selfie_with_id', models.ImageField(upload_to='kyc_records/selfie/')),
                ('proof_of_address', models.ImageField(blank=True, null=True, upload_to='kyc_records/address/')),
                ('business_registration', models.ImageField(blank=True, null=True, upload_to='kyc_records/business/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.IntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_records', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_history', to='users.vendorprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
