# Generated by Django 5.2.3 on 2026-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_vendorkycrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
