# Generated by Django 5.2.3 on 2025-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='eventmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planifié'), ('live', 'En direct'), ('ended', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventlisting',
            name='special_offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécial pendant l’événement', max_digits=10, null=True),
        ),
    ]
