# Generated by Django 5.2.3 on 2025-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('sale', 'Vente'), ('rental', 'Location')], default='vente', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Neuf'), ('used', 'Occasion')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('sold', 'Vendu'), ('expired', 'Expiré')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
