# Generated by Django 5.2.3 on 2025-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_price_alter_listing_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité disponible'),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité vendue'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('sold', 'Vendu'), ('expired', 'Expiré'), ('out_of_stock', 'Epuisé')], default='active', max_length=15),
        ),
    ]
