# Generated by Django 5.2.3 on 2025-10-16 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_quantity_listing_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1, message="Le prix doit être d'au moins 1 XOF"), django.core.validators.MaxValueValidator(99999999, message='Le prix ne peut pas dépasser 99,999,999 XOF')]),
        ),
    ]
