# Generated by Django 5.2.3 on 2025-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_last_viewed_listing_unique_visitors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingview',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
