# Generated by Django 5.2.3 on 2025-06-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteevent',
            options={'verbose_name': 'Événement favori', 'verbose_name_plural': 'Événements favoris'},
        ),
        migrations.AlterModelOptions(
            name='favoritelisting',
            options={'verbose_name': 'Annonce favorite', 'verbose_name_plural': 'Annonces favorites'},
        ),
    ]
