# Generated by Django 5.2.3 on 2025-07-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
    ]
