# Generated by Django 5.2.3 on 2026-02-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listingview_session_key'),
        ('reviews', '0004_alter_review_options_review_edit_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Annonce spécifique évaluée (pour les avis produits)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='listings.listing'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'review_type', 'listing')},
        ),
    ]
