# Generated by Django 5.2.3 on 2026-02-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listingview_session_key'),
        ('reviews', '0006_alter_review_unique_together_alter_review_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(help_text='Annonce spécifique évaluée (pour les avis produits)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing'),
        ),
    ]
