# Generated by Django 5.2.3 on 2026-02-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listingview_session_key'),
        ('reviews', '0007_alter_review_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_user_per_listing',
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Annonce spécifique évaluée (pour les avis produits)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('reviewer', 'listing'), name='unique_review_per_user_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', True), models.Q(('review_type', 'product'), _negated=True)), fields=('reviewer', 'reviewed', 'review_type'), name='unique_user_review_for_non_product'),
        ),
    ]
