# Generated by Django 5.2.3 on 2025-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Commande'), ('message', 'Message'), ('event', 'Événement'), ('listing', 'Annonce'), ('system', 'Système')], default='system', max_length=50),
        ),
    ]
