# Generated by Django 5.2.3 on 2025-06-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_options_alter_listing_type'),
        ('paniers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='panier',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='paniers.panier')),
            ],
            options={
                'unique_together': {('panier', 'listing')},
            },
        ),
    ]
